apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cloudnative-pg
  namespace: argocd

spec:
  project: homelab

  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg.git
    targetRevision: v1.30.0
    path: releases/cnpg-1.30.0.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true