apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cloudnative-pg
  namespace: argocd

spec:
  project: homelab

  source:
    repoURL: https://github.com/Harish-SN/K8s.git
    targetRevision: main
    path: manifests/operators/cloudnative-pg

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true