grafana:
  enabled: false

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec: {}

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
