apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: otel-collector
  namespace: argocd

spec:
  project: homelab

  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.126.0
      helm:
        valueFiles:
          - $values/values/observability/otel-collector-values.yaml

    - repoURL: https://github.com/Harish-SN/K8s.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
