apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tempo
  namespace: argocd

spec:
  project: homelab

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.23.4
      helm:
        valueFiles:
          - $values/values/observability/tempo-values.yaml

    - repoURL: https://github.com/Harish-SN/K8s.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
